[env:controller_w]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<w_controller/*>
; ONEWIRE_CRC16=0: disables OneWire's crc16() method which references _crc16_update
; from avr-libc but ModbusMaster's src/util/crc16.h shadows that header. DallasTemperature
; only uses CRC8 so this is safe.
build_flags = -DONEWIRE_CRC16=0
lib_deps =
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
    adafruit/Adafruit INA219@^1.2.1
    4-20ma/ModbusMaster@^2.0.1

[env:controller_h]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<h_controller/*>
lib_deps =
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
    https://github.com/prenticedavid/MCUFRIEND_kbv/archive/refs/heads/master.zip
    adafruit/Adafruit GFX Library@^1.11.9
    arduino-libraries/SD@^1.2.4
    adafruit/RTClib@^2.1.4